# path of tesseract executable
TESSERACT_PATH: /opt/homebrew/Cellar/tesseract/5.2.0/bin/tesseract
# tolerance in comparing 2 frames
TOLERANCE: 1
# number of frames to skip after every read frame
READ_EVERY_N_FRAMES: 10
# frame to start analisys
START_FRAME: 0
# coords to crop frame to read slide number (in %width, %height)
# [x1,y1,x2,y2]
NUMBER_CROP_BORDERS: [83.5,93,87,99]
# coords to crop the final slide (e.g. to remove black bars)
IMG_CROP_BORDERS: [13,0,87,100]
# path to save
SLIDES_PATH: slides
